@startmindmap
* Metacognition
    ** Goals (objectives)
    ** Actions: \n - Planning \n - Monitoring \n - Evaluation
    ** Experiences: \n - Feelings \n - Reflections
    ** knowledge (believes): \n - Person \n - Task \n - Strategy
@endmindmap